### ISSUE TITLE
[BUG] Minimap and speedometer disappear

### ISSUE THREAD

**Issue by CoZmoTheGod** [Project-Sloth/ps-fuel#10]
QB-Core minimap, speedometer and health, hunger, etc disappeared. I can reset the hub and they show up but the do not work
![image](https://user-images.githubusercontent.com/37917612/184019395-8cbb8bda-7392-4084-9294-3e3254ca1014.png)

**Comment by MonkeyWhisper** [comment]
What does this have to do with ps-fuel?
