### ISSUE TITLE
[BUG] Breaks the new qb-weapons

### ISSUE THREAD

**Issue by w4fflz** [Project-Sloth/ps-fuel#11]
I installed ps-fuel and followed directions exactly as listed in README.  However, after doing so I was not able to reload any weapons in my server and verified with other people that experienced the same issues.  When I uninstalled this script and reverted back to LegacyFuel and adjusted my qb-weapons lua files back to how they are for QBCore foundation, the issues were resolved.   I think this step is breaking ammo reloading

Here is the BUG report I submitted for QB-Weapons: https://github.com/qbcore-framework/qb-weapons/issues/125

![image](https://user-images.githubusercontent.com/96218191/184127908-a7698078-3839-4302-b615-238789b1072c.png)

**Comment by MonkeyWhisper** [comment]
Not a bug, works fine if you follow proper instructions.

https://github.com/Project-Sloth/ps-fuel#jerry-can-saving-correct-amount-left
