### ISSUE TITLE
[Bug] Multiple Bugs plus QBCore Update

### ISSUE THREAD

**Issue by cdnKasu** [Project-Sloth/ps-fuel#17]
- The script does not work with the lasted QBCore updates that removes AddItem.
- The script does not charge what the menu says, it charges the refuel price.
- When you go to refuel the can, most of the time you just start pouring gas on the ground.
- When refueling the can, it doesn't fill all the way up

**Comment by CarlBishop** [comment]
I can confirm.

**Comment by wingdan** [comment]
Try https://github.com/Project-Sloth/ps-fuel/pull/18 and let me know if it helps with the latest QB Core issue (will only fix the AddItem issue)

**Comment by MonkeyWhisper** [comment]
None of those issues have been reported before by other members or confirmed. If you need help, join Discord.
