### ISSUE TITLE
Jerry can empty

### ISSUE THREAD

**Issue by OGReaperx** [Project-Sloth/ps-fuel#20]
Not sure if it's just me and I'm missing something but upon purchasing a jerrycan it goes I to inventory empty, cant refuel vehicle as it says the Jerry can is empty. When you try to refill the jerrycan it does the animation of pouring on the ground, and doesn't refill it.

**Comment by Hitmydabs** [comment]
I did a fix for this issue if you check the pull requests!

**Comment by OGReaperx** [comment]
You are a legend, thank you 🙏

**Comment by OGReaperx** [comment]
> I did a fix for this issue if you check the pull requests!

After adding/replacing your pull request I no longer get given the Jerry can 😅
