### ISSUE TITLE
[Suggestion] Show percentage

### ISSUE THREAD

**Issue by OfficialRDB** [Project-Sloth/ps-fuel#26]
Showing a percentage when filling up along with if you only had $50 bucks to fill up and it only gives you the $50 worth when it should take like $200.

**Comment by xxUnknown13xx** [comment]
> Showing a percentage when filling up along with if you only had $50 bucks to fill up and it only gives you the $50 worth when it should take like $200.

That's the only thing stopping me from using this 🤔
