### ISSUE TITLE
[Bug] Multiple issues

### ISSUE THREAD

**Issue by nzkfc** [Project-Sloth/ps-fuel#3]
There seems to be a few issues that need looking at potentially. I have already submitted the arithmatic error, here are some oddities I noticed as well as our players:

1. Refueling estimates a cost, however it charges what is set in config.lua e.g. `Config.refuelCost = 600`

2. When refueling the car it seems to work fine, however the native gta ammo seems to be misaligned to the item durability which is being used as some sort of quantity remaining function? Pouring the fuel out onto the ground seems to run out way to quickly on the durability but native ammo doesn't match as well as the item ammo in inventory?

3. Seems to get confused sometimes and aims it like a pistol?

4. Seems to randomly pour out after refilling the can.

Here is a clip, might need to pause now and then to review the ammo qty etc to make it make sense: https://drive.google.com/file/d/1T2xpAe--15H5JycAS0tgdWxu6VfYoxeG/view?usp=sharing

**Comment by maguhd** [comment]
In qb-weapons you gotta add weapon_petrolcan in Config.DurabilityBlockedWeapons and remove it from Config.DurabilityMultiplier.

**Comment by MonkeyWhisper** [comment]
Is this still an issue?

> There seems to be a few issues that need looking at potentially. I have already submitted the arithmatic error, here are some oddities I noticed as well as our players:
> 
> 1. Refueling estimates a cost, however it charges what is set in config.lua e.g. `Config.refuelCost = 600`
> 2. When refueling the car it seems to work fine, however the native gta ammo seems to be misaligned to the item durability which is being used as some sort of quantity remaining function? Pouring the fuel out onto the ground seems to run out way to quickly on the durability but native ammo doesn't match as well as the item ammo in inventory?
> 3. Seems to get confused sometimes and aims it like a pistol?
> 4. Seems to randomly pour out after refilling the can.
> 
> Here is a clip, might need to pause now and then to review the ammo qty etc to make it make sense: https://drive.google.com/file/d/1T2xpAe--15H5JycAS0tgdWxu6VfYoxeG/view?usp=sharing

**Comment by nzkfc** [comment]
I'll double check tonight for you and confirm. I know the arithmetic bug is
constantly happening but I get told not to post it here and then when I
post it to support in discord its not looked at. One person mentioned to
look into custom categories in qb-core for vehicles.lua but I'm not sure
what else from there.

**Comment by nzkfc** [comment]
> Is this still an issue?
> 
> > There seems to be a few issues that need looking at potentially. I have already submitted the arithmatic error, here are some oddities I noticed as well as our players:
> > 
> > 1. Refueling estimates a cost, however it charges what is set in config.lua e.g. `Config.refuelCost = 600`
> > 2. When refueling the car it seems to work fine, however the native gta ammo seems to be misaligned to the item durability which is being used as some sort of quantity remaining function? Pouring the fuel out onto the ground seems to run out way to quickly on the durability but native ammo doesn't match as well as the item ammo in inventory?
> > 3. Seems to get confused sometimes and aims it like a pistol?
> > 4. Seems to randomly pour out after refilling the can.
> > 
> > Here is a clip, might need to pause now and then to review the ammo qty etc to make it make sense: https://drive.google.com/file/d/1T2xpAe--15H5JycAS0tgdWxu6VfYoxeG/view?usp=sharing

Yep so working find now, the only thing outstanding is the arithmetic bug, but it's to do with custom categories of cars from vehicles.lua, so there must be a way to incorporate custom categories for the script to work with vehicles.lua

**Comment by MonkeyWhisper** [comment]
> > Is this still an issue?
> > > There seems to be a few issues that need looking at potentially. I have already submitted the arithmatic error, here are some oddities I noticed as well as our players:
> > > 
> > > 1. Refueling estimates a cost, however it charges what is set in config.lua e.g. `Config.refuelCost = 600`
> > > 2. When refueling the car it seems to work fine, however the native gta ammo seems to be misaligned to the item durability which is being used as some sort of quantity remaining function? Pouring the fuel out onto the ground seems to run out way to quickly on the durability but native ammo doesn't match as well as the item ammo in inventory?
> > > 3. Seems to get confused sometimes and aims it like a pistol?
> > > 4. Seems to randomly pour out after refilling the can.
> > > 
> > > Here is a clip, might need to pause now and then to review the ammo qty etc to make it make sense: https://drive.google.com/file/d/1T2xpAe--15H5JycAS0tgdWxu6VfYoxeG/view?usp=sharing
> 
> Yep so working find now, the only thing outstanding is the arithmetic bug, but it's to do with custom categories of cars from vehicles.lua, so there must be a way to incorporate custom categories for the script to work with vehicles.lua

Hmm. Can you share more info on this? The only way this will occur if it's it does not have the proper name on the metadata and on QBCore shared vehicles, meaning the categories to matching qbcore share

**Comment by nzkfc** [comment]
> 

Yeah so as an example of a vehicle that has a custom category:

```
	['dragoon'] = {													
		['name'] = 'Dragoon (Warriors)',
		['brand'] = 'Motorcycle',
		['model'] = 'dragoon',
		['price'] = 75000,
		['category'] = 'gangbike',
		['hash'] = `dragoon`,
		['shop'] = 'motorcycleshop',
	},```
