### ISSUE TITLE
Jerry cans completely unusable

### ISSUE THREAD

**Issue by IKKaybe** [Project-Sloth/ps-fuel#5]
Have followed all the steps in readme to get them working however they just don't seem to work.

Buying one gives it 0 ammo
Takes a few tries to actually get the item out

[Video](https://streamable.com/23o3ko)

**Comment by C17DAGOAT** [comment]
having same issue

**Comment by IKKaybe** [comment]
Any update on this?

**Comment by MonkeyWhisper** [comment]
All works fine, 

https://github.com/Project-Sloth/ps-fuel#jerry-can-saving-correct-amount-left

Follow the proper read me
