### ISSUE TITLE
qb-hud no such GetFuel export

### ISSUE THREAD

**Issue by Niko7133** [Project-Sloth/ps-fuel#54]
I followed all the steps to the letter, but when I get into the vehicle this happen
![parsecd_MDba9LSHmD](https://github.com/Project-Sloth/ps-fuel/assets/64557207/db63ad0d-612f-4387-b03e-2e20c1faa606)

But it's all there in the code
![mstsc_NeG7lAHg3y](https://github.com/Project-Sloth/ps-fuel/assets/64557207/2b39bdb8-ee50-4479-ad78-5211a2231d02)
![mstsc_gsDmnPvENU](https://github.com/Project-Sloth/ps-fuel/assets/64557207/df94dc10-a1e8-46e1-8031-691e34ac8a8b)

**Comment by complexza** [comment]
Using the wrong resource, Screenshots how qb-fuel, ps-fuel replaces qb-fuel, make sure its started.
