### ISSUE TITLE
Closed issue not solved?

### ISSUE THREAD

**Issue by PCL-CrisKolkman** [Project-Sloth/ps-fuel#57]
My issue #56 has been closed as completed but what has been done to fix it?
I see no comments in the issue and also no updated code.

**Comment by MonkeyWhisper** [comment]
Open source, fix it yourself if you want. Stop making issues for your support.

**Comment by PCL-CrisKolkman** [comment]
@MonkeyWhisper You should maybe be a bit more respectful to users.
Why should I fix it myself while the problem is in the script?

**Comment by MonkeyWhisper** [comment]
> @MonkeyWhisper You should maybe be a bit more respectful to users. Why should I fix it myself while the problem is in the script?

What part of "open source" do you not understand? Just to explain it to you, it means you have FULL SOURCE CODE ACCESS. 

Either fix it yourself or don't, couldn't careless what you think. 

Life is hard, wear a helmet. 

You're also now blocked from all Project Sloth resources.
