### ISSUE TITLE
Jerry can unlimited fuel

### ISSUE THREAD

**Issue by Griefa** [Project-Sloth/ps-fuel#6]
When you drop the jerry can and pick it back up, it refills it to 88 

(Yes, I have done the readme correctly)

**Comment by pushkart2** [comment]
that means you have not done changes in smallresources and inventory

**Comment by MonkeyWhisper** [comment]
Fix your stuff. 

Works fine if you look here https://github.com/Project-Sloth/ps-fuel#jerry-can-saving-correct-amount-left
