### ISSUE TITLE
ps-fuel install guide steps 4 and 5

### ISSUE THREAD

**Issue by anotgrass** [Project-Sloth/ps-fuel#68]
In steps 4 and 5 ( they are mislabeled 3 and 4 in the guide)

if weaponName == "weapon_petrolcan" or weaponName == "weapon_fireextinguisher" 
does not exist in qb-inventory/client/main   
https://github.com/qbcore-framework/qb-inventory/blob/main/client/main.lua

and TriggerServerEvent("weapons:server:UpdateWeaponAmmo", CurrentWeaponData, tonumber(ammo)) 
does not exist in qb-weapons/client/main  
https://github.com/qbcore-framework/qb-weapons/blob/main/client/main.lua

How do we proceed with installation if that's the case?

**Comment by MonkeyWhisper** [comment]
Find the right events and replace.
