### ISSUE TITLE
[BUG] Jerry Can Ammo

### ISSUE THREAD

**Issue by MidnightGamingNetwork** [Project-Sloth/ps-fuel#7]
I have followed the step by step guide in the read me. The issue I am having is when the ammo amount for the jerry can is at 18 and you use it to fill a vehicle up, it will fill the whole vehicle and show another ammo amount instead of the jerry can being empty. For example if the jerry can is at 18 and you use it on a vehicle. When you take jerry can back out it will show it now at 28. The jerry can is now unlimited fuel without it ever running out.

I do see that the jerry can has a durability level. Will that effect it at all?

**Comment by MonkeyWhisper** [comment]
https://github.com/Project-Sloth/ps-fuel#jerry-can-saving-correct-amount-left
